export const FRAPPE_UI_COMPONENTS = [
	"Alert",
	"Autocomplete",
	"Avatar",
	"Badge",
	"Button",
	"Breadcrumbs",
	"Checkbox",
	"Calendar",
	"CodeEditor",
	"Combobox",
	"ContextMenu",
	"DatePicker",
	"TimePicker",
	"DateTimePicker",
	"DateRangePicker",
	"MonthPicker",
	"Dialog",
	"Divider",
	"Dropdown",
	"Duration",
	"ErrorMessage",
	"FeatherIcon",
	"FileUploader",
	"FormLabel",
	"FormControl",
	"ListView",
	"MultiSelect",
	"Pill",
	"Progress",
	"Rating",
	"Select",
	"Sidebar",
	"Slider",
	"Spinner",
	"Switch",
	"Tabs",
	"TabButtons",
	"Textarea",
	"TextInput",
	"TextEditor",
	"Tooltip",
	"Tree",
	"AxisChart",
	"NumberChart",
	"DonutChart",
]
export const FRAPPE_COMPONENTS = ["Filter", "Link"]
export const STUDIO_COMPONENTS = [
	"Container",
	"FitContainer",
	"Repeater",
	"HTML",
	"SplitView",
	"AvatarCard",
	"CardList",
	"Audio",
	"ImageView",
	"TextBlock",
	"AppHeader",
	"BottomTabs",
	"MarkdownEditor",
]

// Matches strings that are entirely wrapped in double curly braces, e.g., "{{ expression }}" (allows whitespace inside)
export const DYNAMIC_EXPRESSION_REGEX = /^\{\{[\s\S]*\}\}$/

// Match a double-quoted string and capture its inner content, including escaped chars.
// This pattern safely captures the contents of a JSON-style double-quoted string,
// preserving escaped sequences (e.g. \" or \\n) in the captured group.
export const QUOTED_STRING_CONTENT_REGEX = /"((?:[^"\\]|\\.)*)"/g
