export const FRAPPE_UI_COMPONENTS = [
	"Alert",
	"Autocomplete",
	"Avatar",
	"Badge",
	"Button",
	"Breadcrumbs",
	"Card",
	"Checkbox",
	"Calendar",
	"Combobox",
	"DatePicker",
	"TimePicker",
	"DateTimePicker",
	"DateRangePicker",
	"Dialog",
	"Divider",
	"Dropdown",
	"ErrorMessage",
	"FeatherIcon",
	"FileUploader",
	"FormLabel",
	"FormControl",
	"ListView",
	"Progress",
	"Rating",
	"Select",
	"Switch",
	"Tabs",
	"TabButtons",
	"Textarea",
	"TextInput",
	"TextEditor",
	"Tooltip",
	"Tree",
	"AxisChart",
	"NumberChart",
	"DonutChart",
]
export const FRAPPE_COMPONENTS = ["Link"]
export const STUDIO_COMPONENTS = [
	"Container",
	"FitContainer",
	"Repeater",
	"Header",
	"Sidebar",
	"SplitView",
	"AvatarCard",
	"CardList",
	"Audio",
	"ImageView",
	"TextBlock",
	"AppHeader",
	"BottomTabs",
	"MarkdownEditor",
]

// Matches: "function", "async function", "() =>", "(x) =>", "x =>", "({ x }) =>", "async () =>", etc.
export const FUNCTION_STRING_REGEX = /^(async\s+)?(function\b|(\([^)]*\)|[a-zA-Z_$][a-zA-Z0-9_$]*)\s*=>)/

// Matches strings that are entirely wrapped in double curly braces, e.g., "{{ expression }}" (allows whitespace inside)
export const DYNAMIC_EXPRESSION_REGEX = /^\{\{[\s\S]*\}\}$/
